import { charts } from "@/data/portfolio";
import { Reveal, SectionHeading } from "@/components/portfolio/Primitives";
import Figure from "@/components/portfolio/Figure";

/**
 * /charts — a gallery of the self-analytics visualizations Bhaskar generated
 * with his own Python/matplotlib pipeline (my-portfolio-analytics repo).
 * Presented as editorial figure plates: hairline frames + numbered captions.
 */
export default function Charts() {
  return (
    <div className="pt-32">
      <section className="mx-auto max-w-6xl px-6 sm:px-10">
        <SectionHeading
          eyebrow="Portfolio analytics"
          title={
            <>
              I analyzed <span className="text-primary">myself</span>
            </>
          }
          description="I treat my own portfolio as a dataset — these visualizations are generated by my Python / matplotlib pipeline from my GitHub repos and auto-updated as I ship. A data analyst's site should show the analysis."
        />
      </section>

      <section className="mx-auto max-w-6xl px-6 pt-14 sm:px-10">
        <div className="grid gap-x-10 gap-y-14 md:grid-cols-2">
          {charts.map((c, i) => (
            <Reveal key={c.caption} delay={i * 0.06}>
              <Figure
                src={c.src}
                alt={c.alt}
                index={String(i + 1).padStart(2, "0")}
                caption={c.caption}
                source="PYTHON · MATPLOTLIB"
                ratio={c.ratio ?? "aspect-[16/10]"}
              />
            </Reveal>
          ))}
        </div>

        <Reveal delay={0.15}>
          <p className="mt-14 font-mono2 text-[11px] uppercase tracking-[0.25em] text-muted-foreground">
            Charts regenerate automatically as new projects ship → see the{" "}
            <a
              href="https://github.com/bhaskarpal1707/my-portfolio-analytics"
              target="_blank"
              rel="noreferrer"
              className="link-sweep text-foreground"
            >
              pipeline repo ↗
            </a>
          </p>
        </Reveal>
        <Reveal delay={0.2}>
          <p className="mt-3 font-mono2 text-[11px] uppercase tracking-[0.25em] text-muted-foreground">
            Sankey, sunburst &amp; heatmap plates available in the same repo
          </p>
        </Reveal>
      </section>
    </div>
  );
}
