import { skillGroups, marqueeSkills, charts } from "@/data/portfolio";
import { Reveal, SectionHeading } from "@/components/portfolio/Primitives";
import { SkillTile } from "@/components/portfolio/SkillLogo";
import Marquee from "@/components/portfolio/Marquee";
import Figure from "@/components/portfolio/Figure";

/**
 * Skills — the old portfolio's skill groups rendered as interactive logo
 * tiles. Every tile lifts, glows ember, and re-tints its brand mark on
 * hover; marquees bookend the page for the premium-motion feel.
 */
export default function Skills() {
  let tileIndex = 0;

  return (
    <div className="pt-32">
      <section className="mx-auto max-w-6xl px-6 sm:px-10">
        <SectionHeading
          eyebrow="04 — Skills"
          title={
            <>
              The <span className="text-primary">toolkit</span>, indexed
            </>
          }
          description="Every tool I reach for — from SQL engines to deep-learning frameworks to the annotation stack behind my computer-vision work. Hover any tile."
        />
      </section>

      <section className="mt-12 border-y border-border">
        <Marquee items={marqueeSkills} duration={46} />
      </section>

      {skillGroups.map((group, gi) => (
        <section
          key={group.title}
          className={`mx-auto max-w-6xl px-6 py-14 sm:px-10 ${gi > 0 ? "border-t border-border" : ""}`}
        >
          <Reveal>
            <div className="flex flex-wrap items-baseline justify-between gap-3">
              <h2 className="font-display text-xl font-semibold tracking-tight text-foreground sm:text-2xl">
                <span className="mr-3 font-mono2 text-xs tracking-[0.25em] text-primary">
                  {String(gi + 1).padStart(2, "0")}
                </span>
                {group.title}
              </h2>
              <span className="font-mono2 text-[11px] uppercase tracking-[0.25em] text-muted-foreground">
                {group.skills.length} tools
              </span>
            </div>
          </Reveal>

          <div
            className="mt-7 grid gap-3"
            style={{
              gridTemplateColumns: `repeat(auto-fill, minmax(${Math.min(
                150,
                Math.max(96, 640 / Math.max(2, group.skills.length)),
              )}px, 1fr))`,
            }}
          >
            {group.skills.map((s) => {
              const i = tileIndex++;
              return (
                <Reveal key={s.name} delay={Math.min(0.3, i * 0.03)} y={14}>
                  <SkillTile name={s.name} logo={s.logo} index={i} />
                </Reveal>
              );
            })}
          </div>
        </section>
      ))}

      <section className="mt-2 border-t border-border">
        <Marquee items={[...marqueeSkills].reverse()} duration={52} reverse />
      </section>

      {/* proof-of-skill figure */}
      <section className="mx-auto max-w-6xl border-t border-border px-6 py-20 sm:px-10">
        <SectionHeading
          eyebrow="Proof of skill"
          title={
            <>
              Measured, not <span className="text-primary">claimed</span>
            </>
          }
          description="This chart is generated by my own Python/matplotlib pipeline from my public GitHub repos — the top 20 tools by real usage across every project I've shipped."
        />
        <div className="mx-auto mt-12 max-w-3xl">
          <Reveal>
            <Figure
              src={charts[1].src}
              alt={charts[1].alt}
              index="01"
              caption={charts[1].caption}
              source="PYTHON · MATPLOTLIB · AUTO-UPDATED"
              ratio="aspect-[16/10]"
            />
          </Reveal>
        </div>
      </section>
    </div>
  );
}
