/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  PORTFOLIO CONTENT — edit this file to update anything on the site.
 *  All links/images below are the EXACT ones from the old portfolio
 *  (bhaskarpal1707.github.io/portfolio + its Google Sheets data source).
 * ─────────────────────────────────────────────────────────────────────────────
 */

import portraitImg from "@/assets/bhaskar-portrait.jpg";
import aboutImg from "@/assets/bhaskar-about.jpg";

// Self-analytics charts — generated by Bhaskar's own Python/matplotlib
// pipeline in the my-portfolio-analytics repo (auto-updated from GitHub).
import chordImg from "@/assets/charts/chord.png";
import skillsTopImg from "@/assets/charts/skills-top20.png";
import projectsByTechImg from "@/assets/charts/projects-by-tech.png";
import projectsByDomainImg from "@/assets/charts/projects-by-domain.png";

export type Chart = {
  src: string;
  alt: string;
  caption: string;
  ratio?: string;
};

export const charts: Chart[] = [
  {
    src: chordImg,
    alt: "Chord diagram connecting project domains through shared tools",
    caption: "Project domains × shared tools",
    ratio: "aspect-[4/3]",
  },
  {
    src: skillsTopImg,
    alt: "Bar chart of top 20 skills across all projects",
    caption: "Top 20 skills by usage",
    ratio: "aspect-[16/10]",
  },
  {
    src: projectsByTechImg,
    alt: "Projects grouped by core technology",
    caption: "Projects by technology",
    ratio: "aspect-[16/10]",
  },
  {
    src: projectsByDomainImg,
    alt: "Projects grouped by analytical domain",
    caption: "Projects by domain",
    ratio: "aspect-[16/10]",
  },
];

/** GitHub repo → opengraph preview card (live, always in sync with the repo). */
export const repoOgImage = (githubUrl: string) =>
  `https://opengraph.githubassets.com/1/${githubUrl.replace("https://github.com/", "")}`;

export const profile = {
  name: "Bhaskar Pal",
  firstName: "Bhaskar",
  lastName: "Pal",
  roles: ["Aspiring Data Analyst", "BI Developer", "Data Science Enthusiast", "Analytical Thinker", "Data Insights Creator"],
  tagline: "Turning raw numbers into growth catalysts.",
  headline: "Data Strategist | Insight Architect | Turning Raw Numbers into Growth Catalysts",
  about:
    "I transform raw data into clear, actionable stories that empower smarter decisions. As a data professional, I bridge the gap between complex numbers and strategic business moves. My passion? Turning chaos into clarity — so leaders can act with confidence.",
  location: "Kolkata, West Bengal, India",
  email: "bhaskarpal.official@gmail.com",
  phone: "+91-73188285978",
  github: "https://github.com/bhaskarpal1707",
  linkedin: "https://www.linkedin.com/in/bhaskar-pal-2k02/",
  avatar: portraitImg,
  aboutImage: aboutImg,
  /** Resume — the same Google Drive file the old site links. */
  resume: "https://drive.google.com/file/d/1rqjdT888oIsz3DiDzslP8XZMfqAkaYbF/view?usp=sharing",
  /** Intro video — same YouTube embed the old site opens from About. */
  videoUrl: "https://www.youtube.com/embed/qsH_QY-3SuY",
  /** Google Apps Script endpoint the old contact form posts to. */
  formEndpoint:
    "https://script.google.com/macros/s/AKfycbwTsBgV7aN8eO0XNhnBjEtWY8skoHvcQjsYQP5ParGwPtW0kDBJdBoda9cT4MmURBFnZQ/exec",
};

/** Social handles shown in the hero, footer and contact CTA. */
export type Social = {
  label: string;
  url: string;
  icon: "linkedin" | "github" | "facebook" | "x" | "huggingface" | "mail";
  handle: string;
};

export const socials: Social[] = [
  {
    label: "LinkedIn",
    url: "https://www.linkedin.com/in/bhaskar-pal-2k02/",
    icon: "linkedin",
    handle: "in/bhaskar-pal-2k02",
  },
  {
    label: "GitHub",
    url: "https://github.com/bhaskarpal1707",
    icon: "github",
    handle: "@bhaskarpal1707",
  },
  {
    label: "Facebook",
    url: "https://www.facebook.com/bhaskar.pal.120885",
    icon: "facebook",
    handle: "bhaskar.pal.120885",
  },
  {
    label: "X (Twitter)",
    url: "https://x.com/bhaskarpal_1707?t=mLQH8LZpYDWf80woUswk6g&s=09",
    icon: "x",
    handle: "@bhaskarpal_1707",
  },
  {
    label: "Hugging Face",
    url: "https://huggingface.co/bhaskarpal1707",
    icon: "huggingface",
    handle: "bhaskarpal1707",
  },
];

export const navLinks = [
  { label: "Home", to: "/" },
  { label: "About", to: "/about" },
  { label: "Experience", to: "/experience" },
  { label: "Skills", to: "/skills" },
  { label: "Education", to: "/education" },
  { label: "Projects", to: "/projects" },
  { label: "Certifications", to: "/certifications" },
  { label: "Contact", to: "/contact" },
];

export const impactPoints = [
  {
    title: "Visualize Insights",
    body: "Crafting intuitive Power BI dashboards that make trends leap off the screen.",
    glyph: "◈",
  },
  {
    title: "Uncover Hidden Opportunities",
    body: "Mining data with SQL / Python to reveal growth levers others miss.",
    glyph: "◇",
  },
  {
    title: "Build Trusted Foundations",
    body: "Transforming messy data into clean, analysis-ready models.",
    glyph: "◆",
  },
  {
    title: "Deliver Actionable Intelligence",
    body: "Designing reports that turn insights into strategic next steps.",
    glyph: "✦",
  },
  {
    title: "Predictive Power",
    body: "Building ML models to make predictions and reveal hidden patterns.",
    glyph: "✧",
  },
];

export type Experience = {
  role: string;
  period: string;
  org: string;
  orgUrl: string;
  points: string[];
  tags: string[];
  /** Roadmap coordinates — the storytelling journey line on /experience. */
  station: number; // 0..1 position along the roadmap
  metric: string;
  metricLabel: string;
};

export const experiences: Experience[] = [
  {
    role: "Research Intern",
    period: "Apr, 2026 — Present",
    org: "Indian Statistical Institute, Kolkata",
    orgUrl: "https://www.isical.ac.in/",
    points: [
      "Conducted research in multilingual speech processing and automatic speech recognition (ASR), adapting pretrained speech models for low-resource Bengali using Python, PyTorch, and fairseq2.",
      "Designed and executed experiments involving speech dataset preparation, audio preprocessing, model fine-tuning, and Word Error Rate (WER) evaluation across multiple model configurations.",
      "Expanded a noisy, real-world Bengali speech corpus by curating and validating additional speech samples, while performing error analysis, model evaluation, and documenting experimental findings to support ongoing ASR research.",
    ],
    tags: ["Python", "PyTorch", "fairseq2", "ASR", "WER"],
    station: 1,
    metric: "ASR",
    metricLabel: "Bengali speech research",
  },
  {
    role: "Trainee Intern (Software Development)",
    period: "Jan, 2026 — Mar, 2026",
    org: "IDEAS Technology Innovation Hub @ Indian Statistical Institute, Kolkata",
    orgUrl: "https://www.ideas-tih.org/",
    points: [
      "Established end-to-end workflows for keypoint annotation, object tracking, and semantic segmentation using tools like Label Studio, CVAT, and Fiji/ImageJ.",
      "Performed large-scale keypoint labeling and object tracking on thermal image datasets, including validation, correction, and iterative improvements.",
      "Conducted semantic segmentation of aerial imagery using polygon-based annotation, ensuring high accuracy and dataset consistency.",
      "Developed Python scripts to visualize annotations, tracking trajectories, and segmentation outputs for improved analysis and quality verification.",
      "Deployed and configured annotation platforms (Label Studio and CVAT) on Ubuntu using Docker, and explored open-source models like Qwen2.5-VL-3B and Grounding DINO with supporting Colab notebooks and documentation.",
    ],
    tags: ["Label Studio", "CVAT", "Fiji/ImageJ", "Docker", "Python", "Qwen2.5-VL"],
    station: 0.62,
    metric: "CV",
    metricLabel: "Vision annotation pipelines",
  },
  {
    role: "Trainee Intern",
    period: "Nov, 2025 — Dec, 2025",
    org: "Indian Statistical Institute, Kolkata",
    orgUrl: "https://www.isical.ac.in/",
    points: [
      "Worked on deep learning–based automatic speech recognition (ASR) under faculty supervision, focusing on improving audio preprocessing and recognition accuracy.",
      "Studied and analyzed recent ASR research, with emphasis on feature extraction, speech enhancement, and end-to-end model architectures.",
      "Designed and ran controlled experiments using tools like Librosa, DeepFilterNet, and SepFormer for audio preprocessing, speech separation, and evaluation.",
      "Built prototype pipelines for data preparation, feature engineering, and early-stage model testing to support iterative experimentation.",
      "Conducted structured testing and error analysis, while maintaining clear documentation of experiment setups, code, and results to support reproducibility and improvements.",
    ],
    tags: ["Librosa", "DeepFilterNet", "SepFormer", "Deep Learning"],
    station: 0.28,
    metric: "DL",
    metricLabel: "Deep learning foundations",
  },
];

/* ───────────────────────────── SKILLS ─────────────────────────────
 * Logos resolve through <SkillLogo/> (Devicon components + hand-drawn
 * brand marks for logos no longer in the icon sets).
 * Headings are copied verbatim from the old portfolio.
 * ─────────────────────────────────────────────────────────────────── */

export type Skill = { name: string; logo: string };

export const skillGroups: { title: string; skills: Skill[] }[] = [
  {
    title: "Programming Languages & Query Languages",
    skills: [
      { name: "Python", logo: "python" },
      { name: "SQL", logo: "sql" },
    ],
  },
  {
    title: "Databases & SQL Engines",
    skills: [
      { name: "PostgreSQL", logo: "postgresql" },
      { name: "MySQL", logo: "mysql" },
    ],
  },
  {
    title: "Core Python Libraries",
    skills: [
      { name: "NumPy", logo: "numpy" },
      { name: "Pandas", logo: "pandas" },
      { name: "Matplotlib", logo: "matplotlib" },
      { name: "Seaborn", logo: "seaborn" },
      { name: "scikit-learn", logo: "scikitlearn" },
      { name: "TensorFlow", logo: "tensorflow" },
      { name: "PyTorch", logo: "pytorch" },
      { name: "OpenCV", logo: "opencv" },
      { name: "Librosa", logo: "librosa" },
    ],
  },
  {
    title: "Statistical & Machine Learning Techniques",
    skills: [
      { name: "Supervised Learning", logo: "supervised" },
      { name: "Unsupervised Learning", logo: "unsupervised" },
      { name: "Statistical Analysis", logo: "stats" },
      { name: "Model Evaluation & Validation", logo: "validation" },
    ],
  },
  {
    title: "Business Intelligence & Data Visualization",
    skills: [
      { name: "Excel", logo: "excel" },
      { name: "Spreadsheet", logo: "spreadsheet" },
      { name: "Power BI", logo: "powerbi" },
      { name: "Tableau", logo: "tableau" },
    ],
  },
  {
    title: "Development Environments & IDEs",
    skills: [
      { name: "Visual Studio Code", logo: "vscode" },
      { name: "PyCharm", logo: "pycharm" },
      { name: "Jupyter Notebook", logo: "jupyter" },
      { name: "Google Colab", logo: "colab" },
      { name: "StarUML", logo: "staruml" },
      { name: "Weka", logo: "weka" },
      { name: "GitHub", logo: "github" },
    ],
  },
  {
    title: "Visual Data Annotation Stack",
    skills: [
      { name: "CVAT", logo: "cvat" },
      { name: "Fiji", logo: "fiji" },
      { name: "Label Studio", logo: "labelstudio" },
    ],
  },
];

export type Education = {
  degree: string;
  school: string;
  period: string;
  scoreLabel: string;
  score: string;
  resultUrl: string;
};

export const education: Education[] = [
  {
    degree: "Master of Computer Applications (MCA)",
    school: "Sister Nivedita University",
    period: "Sep 2023 — Jun 2025",
    scoreLabel: "CGPA",
    score: "7.96",
    resultUrl:
      "https://drive.google.com/file/d/1gGVP4eCzIvwUSB4feYYVD3vI8-7dhRsk/view?usp=sharing",
  },
  {
    degree: "Bachelor of Computer Applications (BCA)",
    school: "Techno Main Salt Lake",
    period: "Nov 2020 — Jul 2023",
    scoreLabel: "CGPA",
    score: "8.99",
    resultUrl:
      "https://drive.google.com/file/d/1RLdwbKibmqYNIRbPGJE89v3vrfRJCg_u/view?usp=drive_link",
  },
  {
    degree: "12th Boards (WBCHSE)",
    school: "Malangapara KCB Institution",
    period: "2020",
    scoreLabel: "PERCENTAGE",
    score: "77.4%",
    resultUrl:
      "https://drive.google.com/file/d/1bsX_-FfvwiFkc93iRzhsQYrP1rJA_MRV/view?usp=sharing",
  },
  {
    degree: "10th Boards (WBBSE)",
    school: "Malangapara KCB Institution",
    period: "2018",
    scoreLabel: "PERCENTAGE",
    score: "66.6%",
    resultUrl:
      "https://drive.google.com/file/d/11-8Yp5sBTch6rHP6pEpz8KtyDLtO_i5Y/view?usp=sharing",
  },
];

/* ──────────────────────────── PROJECTS ────────────────────────────
 * All 37 rows copied verbatim from the old portfolio's Google Sheet —
 * exact titles, subtitles, images, GitHub and LinkedIn links. Tags use
 * the sheet's own keywords (End To End / Excel / Power BI / Tableau /
 * SQL / Python / Machine Learning) so the filter tabs match the old
 * site one-to-one.
 * ─────────────────────────────────────────────────────────────────── */

export type Project = {
  title: string;
  tags: string[];
  year: string;
  tech: string[];
  description: string;
  githubUrl: string;
  linkedinUrl: string;
  image: string;
  featured?: boolean;
};

export const projectTags = [
  "All",
  "End To End",
  "Excel",
  "Power BI",
  "Tableau",
  "SQL",
  "Python",
  "Machine Learning",
];

const LI = "https://www.linkedin.com/in/bhaskar-pal-2k02/";

const P = (
  title: string,
  description: string,
  image: string,
  tech: string[],
  keywords: string,
  githubUrl: string,
  linkedinUrl: string,
  featured = false,
): Project => ({
  title,
  tags: keywords
    .split(",")
    .map((k) => k.trim())
    .filter(Boolean),
  year: "",
  tech,
  description,
  githubUrl,
  linkedinUrl: linkedinUrl || LI,
  image: image.startsWith("https://github.com/") ? repoOgImage(image) : image,
  featured,
});

export const projects: Project[] = [
  P(
    "Vendor Performance Analysis – Retail Inventory & Sales",
    "Analyzing vendor efficiency and profitability to drive data-informed purchasing, pricing, and inventory decisions using SQL, Python, and Power BI.",
    "https://lh3.googleusercontent.com/d/1x-Mg6GJz-z-yAyqHDeckYlNmqA-bB9jv",
    ["Python", "SQL", "Power BI", "Jupyter Notebook"],
    "End To End, Power BI",
    "https://github.com/bhaskarpal1707/vendor-performance-analysis-sql-python-powerbi",
    "https://www.linkedin.com/posts/bhaskar-pal-2k02_vendor-performance-analysis-report-activity-7358839896146407426-nANX?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
    true,
  ),
  P(
    "Walmart Sales Data Analysis",
    "Unveiling Key Sales Insights Through Data-Driven Analysis",
    "https://lh3.googleusercontent.com/d/1jV782qoL4JaI1eX8B1W9Vsp-lcJXc8W_",
    ["MySQL Workbench", "Python"],
    "End To End",
    "https://github.com/bhaskarpal1707/Walmart_Sales_Analysis",
    "https://www.linkedin.com/posts/bhaskar-pal-2k02_walmart-sales-data-analysis-activity-7312942147429666816-KYE6?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
    true,
  ),
  P(
    "Comprehensive Banking Risk Analysis",
    "This project focuses on banking risk analytics to enable smarter lending decisions and minimize financial losses.",
    "https://lh3.googleusercontent.com/d/1Qf43c2ODt2xK6E3jBQPbX16Quh9MgQDb",
    ["Python", "SQL", "MySQL", "MS Excel", "Power BI", "Jupyter Notebook"],
    "End To End, Power BI",
    "https://github.com/bhaskarpal1707/bhaskarpal1707-Banking-Risk-Insights-Project",
    "https://www.linkedin.com/feed/update/urn:li:activity:7332306636587393024?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
    true,
  ),
  P(
    "Comprehensive Loan Analytics",
    "This project uses Python, SQL, and Power BI to analyze loan applicant data—assessing financial risk, detecting fraud, and uncovering trends—delivering a dashboard for informed lending decisions.",
    "https://lh3.googleusercontent.com/d/1gh_cLzqjMDECVgR2GNuh4lHiwUjTikBA",
    ["Python", "SQL", "MySQL", "MS Excel", "Power BI", "Jupyter Notebook"],
    "End To End, Power BI",
    "https://github.com/bhaskarpal1707/Comprehensive_Loan_Analytics_Dashboard-Power-BI",
    "https://www.linkedin.com/posts/bhaskar-pal-2k02_comprehensive-loan-analytics-dashboard-activity-7342122530700214272-l5n9?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
    true,
  ),
  P(
    "Mind Metrics",
    "A machine learning system that uses survey data to detect and predict depression, anxiety, and stress in university students, enabling early, scalable interventions with Python and open-source tools.",
    "https://lh3.googleusercontent.com/d/1UJkAMB8g3GwlcKRDadDVahdjwgKFOHcx",
    ["Python", "Machine Learning"],
    "Machine Learning",
    "https://github.com/bhaskarpal1707/Mind-Metrics",
    "",
    true,
  ),
  P(
    "Uber Data Analysis",
    "Insights from Data Exploration",
    "https://lh3.googleusercontent.com/d/1rb8X7jl4dRB3Rc5_JJDXzFfK8IiRQIAW",
    ["Jupyter Notebook", "Python"],
    "Python",
    "https://github.com/bhaskarpal1707/Uber-Data-Analysis",
    "https://www.linkedin.com/posts/bhaskar-pal-2k02_uber-data-analysis-project-activity-7304410654944178176-Fu0c?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
  ),
  P(
    "Road Accident Analysis",
    "Data Cleaning, Processing, Analysis & Visualization",
    "https://lh3.googleusercontent.com/d/18IoBeCgtVbBWri7IzGVJOZjLTed0hlEo",
    ["Excel"],
    "Excel",
    "https://github.com/bhaskarpal1707/Road-Accident-Analysis-Excel-",
    "https://www.linkedin.com/posts/bhaskar-pal-2k02_excel-dataanalysis-datavisualization-activity-7305467438815485952-oQak?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
  ),
  P(
    "Customer Churn Analysis in the Telecom Industry",
    "Insights for Retention Strategies",
    "https://lh3.googleusercontent.com/d/16omn2JVMtcs9Qxe9ODDLGMR4yqZNNBGE",
    ["Jupyter Notebook", "Python"],
    "Python",
    "https://github.com/bhaskarpal1707/Customer-Churn-Analysis",
    "https://www.linkedin.com/posts/bhaskar-pal-2k02_customer-churn-analysis-in-the-telecom-industry-activity-7308569451409416192-7Fg8?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
  ),
  P(
    "Blinkit Analysis Project",
    "Comprehensive SQL Analysis of Blinkit's Sales, Customer Satisfaction & Inventory",
    "https://lh3.googleusercontent.com/d/1JxhFwl-HwFkizLh9Xi91rm4RJv6gNbNB",
    ["MySQL Workbench"],
    "SQL",
    "https://github.com/bhaskarpal1707/Blinkit-Analysis-SQL-Project",
    "https://www.linkedin.com/posts/bhaskar-pal-2k02_blinkit-analysis-sql-project-activity-7309316361208373248-L_WJ?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
  ),
  P(
    "HR Data Analysis",
    "Interactive Power BI HR Dashboard: Workforce Attrition, Salary & Job Satisfaction Insights",
    "https://lh3.googleusercontent.com/d/1wA8OICrhNWeEIeTAkfCqk_e6pXjmT-V7",
    ["Power BI"],
    "Power BI",
    "https://github.com/bhaskarpal1707/Power-BI-Dashboard-Project-HR-Data-Analysis",
    "https://www.linkedin.com/posts/bhaskar-pal-2k02_powerbi-dataanalytics-hrdataanalysis-activity-7310594501373267968-cKpL?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
  ),
  P(
    "Airbnb Data Analysis",
    "Comprehensive Data Insights using Python",
    "https://lh3.googleusercontent.com/d/13d25Cbu1XUeiE_LtG0DfSo8IszltUE3u",
    ["Jupyter Notebook", "Python"],
    "Python",
    "https://github.com/bhaskarpal1707/Airbnb-Data-Analysis-Project-",
    "https://www.linkedin.com/posts/bhaskar-pal-2k02_airbnb-data-analysis-project-activity-7310663641274429441-xtkF?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
  ),
  P(
    "Online Book Store Analysis",
    "Efficient Data Analysis and Insights Using SQL Queries",
    "https://lh3.googleusercontent.com/d/1UsQVrZiXnsN4aoy89jcxCWrS0vYvNAcl",
    ["PostgreSQL"],
    "SQL",
    "https://github.com/bhaskarpal1707/Online-Bookstore-Analysis",
    "https://www.linkedin.com/posts/bhaskar-pal-2k02_online-bookstore-analysis-activity-7311359748447027201-Qt3c?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
  ),
  P(
    "Indian Weather Data Analysis",
    "Exploring Real-Time Weather Data to Unveil Patterns and Trends Across Indian Cities",
    "https://lh3.googleusercontent.com/d/1Ejw-hY_1_GcJG2cnrxZfZN6UHv74Zp0h",
    ["Jupyter Notebook", "Python"],
    "Python",
    "https://github.com/bhaskarpal1707/Weather_Data_Analysis",
    "https://www.linkedin.com/posts/bhaskar-pal-2k02_indian-weather-analysis-activity-7311907665671008256-v1Ni?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
  ),
  P(
    "Spotify Analysis Project",
    "Analyzes Spotify music data with advanced SQL—focusing on dataset normalization, efficient querying, and insight extraction.",
    "https://lh3.googleusercontent.com/d/1VWD--MOh83t23zRlBz5RRQp3WrBPhSS2",
    ["PostgreSQL"],
    "SQL",
    "https://github.com/bhaskarpal1707/Spotify-Data-Analysis-using-SQL",
    "https://www.linkedin.com/posts/bhaskar-pal-2k02_spotify-advanced-sql-project-and-query-optimization-activity-7314381363334324225-L2GE?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
  ),
  P(
    "Hospital Emergency Room Analysis",
    "An Excel dashboard to visualize ER performance, aiming to streamline operations and support effective hospital decision-making.",
    "https://lh3.googleusercontent.com/d/1PGUt8FcL1Z3d3fEogMx674WWPI1xf03k",
    ["Excel"],
    "Excel",
    "https://github.com/bhaskarpal1707/Hospital-Emergency-Room-Analysis-Using_Excel",
    "",
  ),
  P(
    "Startup Success Analysis",
    "Exploratory data analysis of startup success, leveraging multi-industry data to uncover key growth, funding, and efficiency factors for founders and investors.",
    "https://lh3.googleusercontent.com/d/1CpunGHV2OXQiFYggxA4SY5F98JHTkZnD",
    ["Python"],
    "Python",
    "https://github.com/bhaskarpal1707/Startup-Analysis_Using_Python",
    "https://www.linkedin.com/posts/bhaskar-pal-2k02_decoding-startup-success-activity-7324754346452168704-NWWP?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
  ),
  P(
    "Student Placement Analysis",
    "Analyzes student placement data to reveal key academic and demographic factors affecting campus placement — insights for educators, counselors, and students.",
    "https://lh3.googleusercontent.com/d/1UvsQS8n8axOcjNrA2v-Mla2lSocBuUAM",
    ["Python"],
    "Python",
    "https://github.com/bhaskarpal1707/Student-Placement-Analysis",
    "https://www.linkedin.com/posts/bhaskar-pal-2k02_student-placement-analysis-activity-7330195916852731904-IBPI?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
  ),
  P(
    "Netflix Data Analysis",
    "Uses advanced SQL to analyze Netflix data and uncover insights on content distribution, popularity, and trends.",
    "https://lh3.googleusercontent.com/d/1SEMDrYYUy532YiMoVvOBAaegSeJfv2th",
    ["PostgreSQL"],
    "SQL",
    "https://github.com/bhaskarpal1707/Netflix-Analysis-SQL-Project",
    "https://www.linkedin.com/posts/bhaskar-pal-2k02_netflixanalysissql-activity-7333522049337892866-X8LJ?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
  ),
  P(
    "Loan Risk Analysis",
    "EDA on a loan dataset to improve approval processes by reducing defaults, detecting fraud, and understanding borrower behavior.",
    "https://lh3.googleusercontent.com/d/16vFARKnHQxE3hkLT8NVe-4mdp0EXPNNa",
    ["Jupyter Notebook", "Python"],
    "Python",
    "https://github.com/bhaskarpal1707/Loan-Risk-Analyzer",
    "https://www.linkedin.com/feed/update/urn:li:activity:7334597801240125442?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
  ),
  P(
    "Online Retail Analysis",
    "A Power BI dashboard delivering key insights on online retail sales, customer behavior, product performance, and location data for informed decision-making.",
    "https://lh3.googleusercontent.com/d/1KFjWOtjzIz_4WayNE4NduDNnQbBR0WYr",
    ["Power BI"],
    "Power BI",
    "https://github.com/bhaskarpal1707/Online-Retail-Insights-Dashboard",
    "https://www.linkedin.com/posts/bhaskar-pal-2k02_powerbidashboard-retailanalytics-dataanalyticsproject-activity-7338869530342895617-Brl-?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
  ),
  P(
    "Aircraft Occupancy Optimization",
    "Data analysis helping a business-jet operator boost occupancy, optimize pricing, and increase profit per seat amid rising costs and market pressures.",
    "https://lh3.googleusercontent.com/d/1wsaGm4ji3_fQSMQ9pAyGLy_hGhaZ2HND",
    ["Jupyter Notebook", "Python"],
    "Python",
    "https://github.com/bhaskarpal1707/Airlines-Analysis",
    "https://www.linkedin.com/posts/bhaskar-pal-2k02_airline-analysis-presentation-activity-7339364988496596992-3ycY?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
  ),
  P(
    "Zepto Analyst Project",
    "Hands-on SQL analysis of real Zepto inventory data — the full analyst workflow on over 3,700 product listings.",
    "https://lh3.googleusercontent.com/d/1UiUsstRWiBkvtOJtodnBzmFpmhATl8Xb",
    ["PostgreSQL"],
    "SQL",
    "https://github.com/bhaskarpal1707/Zepto-Analysis-SQL-Project",
    "https://www.linkedin.com/posts/bhaskar-pal-2k02_zepto-analysis-sql-project-activity-7344419051131047937-LNOf?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
  ),
  P(
    "Diwali Sales Analysis",
    "Analyzes Diwali sales data to reveal customer trends, product demand, and regional performance for strategic decision-making.",
    "https://lh3.googleusercontent.com/d/1ShZf6F2o8kNf1SgCryfJX7BmizY47Mi0",
    ["Python"],
    "Python",
    LI,
    "",
  ),
  P(
    "Website Performance Analysis",
    "Analyzes website user sessions using Python to uncover insights on traffic, engagement, and optimization for marketing and content strategies.",
    "https://lh3.googleusercontent.com/d/1Y8p1m_TZxC9IIcvvoKPI7ta6Myw00JDk",
    ["Python"],
    "Python",
    "https://github.com/bhaskarpal1707/Website-Performance-Analysis",
    "https://www.linkedin.com/posts/bhaskar-pal-2k02_website-performance-analysis-presentation-activity-7349854975058997248-LBt2?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
  ),
  P(
    "Google Search Analysis",
    "Uses Python and the Google Trends API to analyze global keyword interest over time and geography with clear visuals and reusable code.",
    "https://lh3.googleusercontent.com/d/1n9sxAkAsCAenm5PqNl4O2qvziAK2-De6",
    ["Python"],
    "Python",
    "https://github.com/bhaskarpal1707/Google-Search-Analysis",
    "https://www.linkedin.com/posts/bhaskar-pal-2k02_google-search-analysis-presentation-activity-7350422642845245440-serA?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
  ),
  P(
    "Boston House Pricing Prediction Analysis",
    "The Boston House Prices Dataset from 1978 — 506 entries with 14 features describing homes across Boston suburbs.",
    "https://lh3.googleusercontent.com/d/1KArtx0zM6sWxd6FDde5LXi8ZvVE9NRXb",
    ["Machine Learning", "Python"],
    "Machine Learning",
    "https://github.com/bhaskarpal1707/boston-house-pricing-prediction-analysis",
    "",
  ),
  P(
    "Online Courses Analysis",
    "Insights-Driven Exploration of the Online Learning Market",
    "https://github.com/bhaskarpal1707/online-courses-analysis-powerbi",
    ["Power BI"],
    "Power BI",
    "https://github.com/bhaskarpal1707/online-courses-analysis-powerbi",
    "https://www.linkedin.com/posts/bhaskar-pal-2k02_powerbi-dataanalytics-edtech-activity-7361340814184124416-L4am?utm_source=share&utm_medium=member_desktop&rcm=ACoAADZ3YJ4BC4Dw2J5XglO82x4Wzs6U1-pZ7So",
  ),
  P(
    "YouTube Data Scraper Analysis",
    "Scraping, Analyzing & Visualizing YouTube Data using the YouTube Data API",
    "https://github.com/bhaskarpal1707/youtube-data-scraper-analysis-python",
    ["Python", "YouTube API"],
    "Python",
    "https://github.com/bhaskarpal1707/youtube-data-scraper-analysis-python",
    "https://lnkd.in/p/gQppW3bu",
  ),
  P(
    "Banking Customer Churn & Risk Analysis",
    "Data-Driven Insights for Reducing Customer Churn and Managing Risk in the Banking Sector",
    "https://github.com/bhaskarpal1707/banking-customers-churn-and-risk-analysis-excel-powerbi",
    ["Excel", "Power BI"],
    "Power BI",
    "https://github.com/bhaskarpal1707/banking-customers-churn-and-risk-analysis-excel-powerbi",
    "https://lnkd.in/p/gHU6QSPw",
  ),
  P(
    "Customers Churn Analysis",
    "Uncovering Drivers of Customer Retention and Reducing Churn through Data Insights",
    "https://github.com/bhaskarpal1707/customers-churn-analysis-python",
    ["Jupyter Notebook", "Python"],
    "Python",
    "https://github.com/bhaskarpal1707/customers-churn-analysis-python",
    "https://lnkd.in/p/gC6UAMi2",
  ),
  P(
    "Spotify Music Trends Analysis",
    "Interactive Analysis of Music Trends, Artists & Listener Preferences",
    "https://github.com/bhaskarpal1707/spotify-analysis-dashboard-powerbi",
    ["Power BI"],
    "Power BI",
    "https://github.com/bhaskarpal1707/spotify-analysis-dashboard-powerbi",
    "https://lnkd.in/p/gtbZ4MQg",
  ),
  P(
    "PhonePe Data Analysis",
    "Analyzing Digital Payment Trends, Transaction Performance & Operational Insights",
    "https://github.com/bhaskarpal1707/phonepe-analysis-powerbi",
    ["Power BI"],
    "Power BI",
    "https://github.com/bhaskarpal1707/phonepe-analysis-powerbi",
    "https://lnkd.in/p/gQzN9vXb",
  ),
  P(
    "E-Commerce Funnel Analysis",
    "Analyzing Customer Journeys, Funnel Drop-Offs & Conversion Drivers",
    "https://github.com/bhaskarpal1707/e-commerce-funnel-analysis",
    ["Jupyter Notebook", "Python"],
    "Python",
    "https://github.com/bhaskarpal1707/e-commerce-funnel-analysis",
    "https://lnkd.in/p/g5_-HgKP",
  ),
  P(
    "AI Language Detection System",
    "Real-Time Multilingual Text Classification with Machine Learning",
    "https://github.com/bhaskarpal1707/Language-Detection-App",
    ["Machine Learning", "Python"],
    "Machine Learning",
    "https://github.com/bhaskarpal1707/Language-Detection-App",
    "https://lnkd.in/p/gxcNf5GC",
  ),
  P(
    "LaTeX OCR",
    "Fine-Tuning a Vision-Language Model for Handwritten & Printed Math-to-LaTeX OCR",
    "https://github.com/bhaskarpal1707/qwen3.5-latex-ocr-finetune-v2",
    ["Machine Learning", "Python"],
    "Machine Learning",
    "https://github.com/bhaskarpal1707/qwen3.5-latex-ocr-finetune",
    "https://lnkd.in/p/gkV8aMVm",
  ),
  P(
    "BanglaSum",
    "Fine-Tuning a Small Language Model for Abstractive Bengali News Summarization",
    "https://github.com/bhaskarpal1707/BanglaSum-Qwen3-XLSum",
    ["Machine Learning", "Python"],
    "Machine Learning",
    "https://github.com/bhaskarpal1707/BanglaSum-Qwen3-XLSum",
    "",
  ),
  P(
    "BanglaVLM",
    "Parameter-Efficient Adaptation of Lightweight Vision-Language Models for Bengali VQA & Cross-Dataset Generalization",
    "https://github.com/bhaskarpal1707/BanglaVLM",
    ["Machine Learning", "Python"],
    "Machine Learning",
    "https://github.com/bhaskarpal1707/BanglaVLM",
    "https://lnkd.in/p/gQh4jNuu",
    true,
  ),
];

/* ───────────────────────── CERTIFICATIONS ─────────────────────────
 * All 28 rows copied verbatim from the old portfolio's Google Sheet —
 * exact names, descriptions, credential links and certificate images.
 * ─────────────────────────────────────────────────────────────────── */

export type Certification = {
  title: string;
  description: string;
  url: string;
  image: string;
};

const C = (title: string, description: string, url: string, image: string): Certification => ({
  title,
  description,
  url,
  image: image.startsWith("https://drive.google.com/file/d/")
    ? `https://lh3.googleusercontent.com/d/${image.split("/d/")[1]?.split("/")[0]}`
    : image,
});

export const certifications: Certification[] = [
  C(
    "Meta Data Analyst Professional Certificate",
    "Core data analytics skills in OSEMN, SQL, spreadsheets, Python, statistics, and data management.",
    "https://www.coursera.org/account/accomplishments/professional-cert/USF2V9DH9W7O",
    "https://lh3.googleusercontent.com/d/1rczayCC81oOMEh4gMOm0XaSUeI2EubJu",
  ),
  C(
    "Data Analyst: Professional Certificate in Data Analysis",
    "Professional Certification in Data Analysis, Analytics & Business Intelligence.",
    "https://www.udemy.com/certificate/UC-fac5694f-3ba6-42bd-9acb-cf28251bab92/",
    "https://lh3.googleusercontent.com/d/1p6OcA3kxK45p6aDHlX14NxAwO2o5DAL0",
  ),
  C(
    "Google Analytics for Beginners",
    "Google Analytics Academy — foundational skills in web analytics and the Google Analytics platform.",
    "https://drive.google.com/file/d/1Tg4-doWsKtPII1JwLmsPHmDz1qjiYmp8/view?usp=sharing",
    "https://lh3.googleusercontent.com/d/1Tg4-doWsKtPII1JwLmsPHmDz1qjiYmp8",
  ),
  C(
    "Data Analytics Essentials",
    "Cisco Data Analytics Essentials — practical skills in data analysis, visualization, Excel, SQL & Tableau.",
    "https://www.credly.com/badges/f4aa0d1d-ffdc-4d6c-9b8f-3d8c73014639/linked_in_profile",
    "https://lh3.googleusercontent.com/d/1s0IzmJPWZ9bGdc7qUUfojaT6HEpb71Ym",
  ),
  C(
    "Introduction to Data Analytics",
    "Meta-authorized course via Coursera — foundational proficiency in data analytics.",
    "https://drive.google.com/file/d/1A0T6m6Ci2Zow_LU-CK_FWVMM0TYhwCWz/view?usp=drive_link",
    "https://lh3.googleusercontent.com/d/1A0T6m6Ci2Zow_LU-CK_FWVMM0TYhwCWz",
  ),
  C(
    "Data Analysis with Spreadsheets and SQL",
    "Meta-authorized course via Coursera — practical data analysis using spreadsheets and SQL.",
    "https://drive.google.com/file/d/1U_3ih4HMO-IHZHYyIhVIFQnBV4RlXExO/view?usp=sharing",
    "https://lh3.googleusercontent.com/d/1U_3ih4HMO-IHZHYyIhVIFQnBV4RlXExO",
  ),
  C(
    "Python Data Analytics",
    "Meta-authorized course via Coursera — practical skills in Python for data analysis.",
    "https://drive.google.com/file/d/1-vGP12RMjN6Z9QEtDqHAfNKUbkzYZvfx/view?usp=sharing",
    "https://lh3.googleusercontent.com/d/1-vGP12RMjN6Z9QEtDqHAfNKUbkzYZvfx",
  ),
  C(
    "Statistics Foundations",
    "Meta-authorized course via Coursera — core knowledge in statistical principles and methods.",
    "https://drive.google.com/file/d/19-dwU3jIKh8X5veKQ9BSFJMScs5iCVOG/view?usp=sharing",
    "https://lh3.googleusercontent.com/d/19-dwU3jIKh8X5veKQ9BSFJMScs5iCVOG",
  ),
  C(
    "Introduction to Data Management",
    "Meta-authorized course via Coursera — foundational data management concepts and practices.",
    "https://drive.google.com/file/d/1yrnPQ5hedWkjm57pEw7BV_EODcSi6_7p/view?usp=sharing",
    "https://lh3.googleusercontent.com/d/1yrnPQ5hedWkjm57pEw7BV_EODcSi6_7p",
  ),
  C(
    "Foundations: Data, Data, Everywhere",
    "Google-authorized course via Coursera — strong understanding of foundational data concepts.",
    "https://drive.google.com/file/d/1HWsS-h_1TRUUX3nP_GyOMcjRmzlpcm9j/view?usp=sharing",
    "https://lh3.googleusercontent.com/d/1HWsS-h_1TRUUX3nP_GyOMcjRmzlpcm9j",
  ),
  C(
    "Extract, Transform and Load Data in Power BI",
    "Microsoft-authorized course via Coursera — proficiency in ETL processes using Power BI.",
    "https://drive.google.com/file/d/1ayXu9P3k8rXnVZlGlPYbrcNr4vp4kp0R/view?usp=sharing",
    "https://lh3.googleusercontent.com/d/1ayXu9P3k8rXnVZlGlPYbrcNr4vp4kp0R",
  ),
  C(
    "Data Modeling in Power BI",
    "Microsoft-authorized course via Coursera — expertise in data modeling techniques using Power BI.",
    "https://drive.google.com/file/d/1yyAniMmnfDL6VBPz6XRJoJQl2PcPizO4/view?usp=sharing",
    "https://lh3.googleusercontent.com/d/1yyAniMmnfDL6VBPz6XRJoJQl2PcPizO4",
  ),
  C(
    "Harnessing the Power of Data with Power BI",
    "Microsoft-authorized course via Coursera — foundational Power BI for data analysis and visualization.",
    "https://drive.google.com/file/d/15ybmZwXYmDlzeUoePlQ-lt2I_0e6LXVQ/view?usp=sharing",
    "https://lh3.googleusercontent.com/d/15ybmZwXYmDlzeUoePlQ-lt2I_0e6LXVQ",
  ),
  C(
    "Preparing Data for Analysis with Microsoft Excel",
    "Microsoft-authorized course via Coursera — data preparation and analysis using Excel.",
    "https://drive.google.com/file/d/1Zf-tdGBVm0onEiWtHYYzAb1Ik04Q9Zm0/view?usp=sharing",
    "https://lh3.googleusercontent.com/d/1Zf-tdGBVm0onEiWtHYYzAb1Ik04Q9Zm0",
  ),
  C(
    "Master Data Management for Beginners",
    "Microsoft-authorized course via Coursera — data management concepts and practices.",
    "https://drive.google.com/file/d/18xt2e2bIFhA5roLc-dy0UzmyoVjTjO4N/view?usp=sharing",
    "https://lh3.googleusercontent.com/d/18xt2e2bIFhA5roLc-dy0UzmyoVjTjO4N",
  ),
  C(
    "Data Science Foundations - Level 2 (V2)",
    "IBM Data Science Foundations — methodologies, statistics, programming and open source tools.",
    "https://www.credly.com/badges/75639298-2fe6-4f5c-9ca3-2ea6a00fecff",
    "https://lh3.googleusercontent.com/d/1cU2q7eAV5dfpnVPB4nnSXY8GRNisFdY7",
  ),
  C(
    "Data Science Tools",
    "Data Science Tools with Jupyter Notebooks, RStudio, IBM Watson Studio and data visualization.",
    "https://www.credly.com/badges/75639298-2fe6-4f5c-9ca3-2ea6a00fecff",
    "https://lh3.googleusercontent.com/d/1efhPg3WUegra7-X5-yPFsvFyy7YYF0ZK",
  ),
  C(
    "Data Science Methodology",
    "Problem solving, data preparation, modeling, evaluation and deployment.",
    "https://drive.google.com/file/d/1yTlTA_KnM8n_84AKhJ-6Fujksp_r_5Rb/view?usp=drive_link",
    "https://lh3.googleusercontent.com/d/1yTlTA_KnM8n_84AKhJ-6Fujksp_r_5Rb",
  ),
  C(
    "Data Science 101",
    "Data science fundamentals, tools, methodologies and real-world applications.",
    "https://drive.google.com/file/d/1-qeR0VGXQlFKtWrTzOYbEiv-WY_yuyZr/view?usp=drive_link",
    "https://lh3.googleusercontent.com/d/1-qeR0VGXQlFKtWrTzOYbEiv-WY_yuyZr",
  ),
  C(
    "SQL and Relational Databases 101",
    "IBM-powered course on Cognitive Class — foundational skills in SQL and relational databases.",
    "https://drive.google.com/file/d/1P95_hpszQkGbIgUbpoxAt9h-jBGBHlhz/view?usp=sharing",
    "https://lh3.googleusercontent.com/d/1P95_hpszQkGbIgUbpoxAt9h-jBGBHlhz",
  ),
  C(
    "Career Essentials in Data Analysis by Microsoft and LinkedIn",
    "Career Essentials in Data Analysis — data analytics and data visualization.",
    "https://www.linkedin.com/learning/certificates/e4fee20a12c4c9a64fe6ad16b4a597637dd84a10223af0b884a7c65b251149c9?trk=share_certificate&lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_certifications_details%3Bg8n2u%2FioS9GdH7ob%2F6z7NA%3D%3D",
    "https://lh3.googleusercontent.com/d/1INLbUo0OeueV09ppwJ_sGZRqaZhmlWSJ",
  ),
  C(
    "Introduction to Career Skills in Data Analytics",
    "Microsoft & LinkedIn Career Essentials — data analytics, visualization & analytical skills.",
    "https://drive.google.com/file/d/1-v90IhW66ZYS82OEMxc5x6u6bGLqPe6H/view?usp=drive_link",
    "https://lh3.googleusercontent.com/d/1-v90IhW66ZYS82OEMxc5x6u6bGLqPe6H",
  ),
  C(
    "Learning Data Analytics: 1 Foundations",
    "LinkedIn Learning — Data Analytics Foundations: core concepts, methods & best practices.",
    "https://www.linkedin.com/learning/certificates/35cb9b323674526606259cd1d4d706c58fbaaa051d45a244b8c5b688c8e106e5?trk=share_certificate&lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_certifications_details%3Bg8n2u%2FioS9GdH7ob%2F6z7NA%3D%3D",
    "https://lh3.googleusercontent.com/d/1x6yI3VLNo4g7MlugE6yHZhJcgAwvqWr1",
  ),
  C(
    "Learning Data Analytics Part 2: Extending and Applying Core Knowledge",
    "LinkedIn Learning — advanced data analytics concepts, applications & practical techniques.",
    "https://www.linkedin.com/learning/certificates/16ab8fa4069c0a87ab0a30da069c9333391ca4098e523d7599bd65429905a829?trk=share_certificate&lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_certifications_details%3Bg8n2u%2FioS9GdH7ob%2F6z7NA%3D%3D",
    "https://lh3.googleusercontent.com/d/1d8lDT1GlAF2NATcEK-LxiTLVc7Y-d_5p",
  ),
  C(
    "Artificial Intelligence Expert Certification (2021 Edition)",
    "18.5-hour Udemy course — proficiency in core AI concepts and applications.",
    "https://drive.google.com/file/d/1wgB08mkq-DGC8T2hcrrM3g_PY_Sphuz3/view?usp=sharing",
    "https://lh3.googleusercontent.com/d/1wgB08mkq-DGC8T2hcrrM3g_PY_Sphuz3",
  ),
  C(
    "The Fundamentals of Digital Marketing",
    "Google Digital Unlocked — foundational digital marketing principles and strategies.",
    "https://drive.google.com/file/d/1K70EQWLboxkeoLCOZymNbDBJJ5C-9Pqm/view?usp=sharing",
    "https://lh3.googleusercontent.com/d/1K70EQWLboxkeoLCOZymNbDBJJ5C-9Pqm",
  ),
  C(
    "Computer Fundamentals: Hardware",
    "Pluralsight course — foundational understanding of computer hardware concepts and components.",
    "https://drive.google.com/file/d/1q66glxgrMCED1zObz1scRzH6b8MxGOs3/view?usp=sharing",
    "https://lh3.googleusercontent.com/d/1q66glxgrMCED1zObz1scRzH6b8MxGOs3",
  ),
  C(
    "Communication Skills",
    "TCS iON online course — effective verbal and non-verbal communication techniques.",
    "https://drive.google.com/file/d/1mJ7IVurCKFg3xfyNVSzBLPsfxFrQMDjK/view?usp=sharing",
    "https://lh3.googleusercontent.com/d/1mJ7IVurCKFg3xfyNVSzBLPsfxFrQMDjK",
  ),
];

export const stats = [
  { value: 37, suffix: "+", label: "Projects shipped" },
  { value: 3, suffix: "", label: "Research internships" },
  { value: 28, suffix: "", label: "Certifications" },
  { value: 5, suffix: "+", label: "Years of code" },
];

/** Experience as file versions — the design-file metaphor for a data career. */
export const versions = [
  {
    tag: "V3 · 26—now",
    org: "Indian Statistical Institute, Kolkata",
    role: "Research Intern",
    period: "Apr, 2026 — Present",
    orgUrl: "https://www.isical.ac.in/",
    note: "Multilingual speech processing & ASR for low-resource Bengali — PyTorch, fairseq2, WER evaluation.",
  },
  {
    tag: "V2 · 26",
    org: "IDEAS Technology Innovation Hub @ ISI",
    role: "Trainee Intern (Software Development)",
    period: "Jan, 2026 — Mar, 2026",
    orgUrl: "https://www.ideas-tih.org/",
    note: "Keypoint annotation, object tracking & segmentation pipelines — Label Studio, CVAT, Fiji, Docker.",
  },
  {
    tag: "V1 · 25",
    org: "Indian Statistical Institute, Kolkata",
    role: "Trainee Intern",
    period: "Nov, 2025 — Dec, 2025",
    orgUrl: "https://www.isical.ac.in/",
    note: "Deep-learning ASR under faculty supervision — Librosa, DeepFilterNet, SepFormer experiments.",
  },
  {
    tag: "A0 · always",
    org: "Foundations",
    role: "Curiosity · Craft · Clean data",
    period: "",
    orgUrl: "",
    note: "The base layer every version compiles on top of.",
  },
];

export const marqueeSkills = [
  "Python",
  "SQL",
  "Power BI",
  "PyTorch",
  "scikit-learn",
  "Pandas",
  "Tableau",
  "PostgreSQL",
  "TensorFlow",
  "Excel",
  "Machine Learning",
  "Data Storytelling",
  "Librosa",
  "OpenCV",
  "MySQL",
  "Label Studio",
];
